[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.54.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo  --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.54.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo  --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.54.0"

[context.branch-deploy]
command = "hugo  --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.54.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
from="/late-2018-reading-list/"
to="/writing/2019-01-02-late-2018-reading-list/"
[[redirects]]
from="/a-small-benediction-2019/"
to="/writing/2019-01-01-a-small-benediction/"
[[redirects]]
from="/climate-grief/"
to="/writing/2018-12-04-climate-grief/"
[[redirects]]
from="/the-incentives-shaping-the-web-amp-google/"
to="/writing/2018-09-10-the-incentives-shaping-the-web/"
[[redirects]]
from="/early-2018-reading-list/"
to="/writing/2018-09-04-early-2018-reading-report/"
[[redirects]]
from="/how-am-i-not-myself/"
to="/writing/2018-08-21-how-am-i-not-myself/"
[[redirects]]
from="/ursula-le-guin-on-seeking-utopia/"
to="/writing/2018-02-12-le-guin-on-seeking-utopia/"
[[redirects]]
from="/2017-year-in-reading/"
to="/writing/2018-01-01-2017-year-in-reading/"
[[redirects]]
from="/behind-the-scenes/"
to="/writing/2017-10-23-behind-the-scenes/"
[[redirects]]
from="/nytmag-alien-messages-global-decisions/"
to="/writing/2017-07-06-nytmag-messaging-extraterrestrials/"
[[redirects]]
from="/book-disability-history-united-states/"
to="/writing/2017-02-17-book-disability-history-of-the-us/"
[[redirects]]
from="/fucking-toomey-townhall-notes/"
to="/writing/2017-02-16-toomey-townhall-notes/"
[[redirects]]
from="/video-quote-intellect-of-woman/"
to="/writing/2017-02-07-video-intellect-of-woman/"
[[redirects]]
from="/book-the-master-switch/"
to="/writing/2017-02-05-book-the-master-switch/"
[[redirects]]
from="/book-hope-in-the-dark/"
to="/writing/2017-02-05-book-hope-in-the-dark/"
[[redirects]]
from="/book-networks-of-new-york/"
to="/writing/2017-01-27-book-networks-of-new-york/"
[[redirects]]
from="/book-americanah/"
to="/writing/2017-01-27-book-americanah/"
[[redirects]]
from="/pa-end-gerrymandering-fair-districts/"
to="/writing/2017-01-26-pa-end-gerrymandering-meeting/"
[[redirects]]
from="/book-the-sixth-exctinction/"
to="/writing/2016-12-27-book-sixth-extinction/"
[[redirects]]
from="/book-white-rage/"
to="/writing/2016-12-09-book-white-rage/"
[[redirects]]
from="/book-empathy-exams/"
to="/writing/2016-12-08-book-the-empathy-exams/"
[[redirects]]
from="/book-on-web-typography/"
to="/writing/2016-12-08-book-on-web-typography/"
[[redirects]]
from="/fighting-trump-with-cognitive-dissonance/"
to="/writing/2016-11-27-how-i-became-liberal-or-fostering-cognitive-dissonance/"
[[redirects]]
from="/sara-hendren-keynote-talk/"
to="/writing/2016-08-30-sara_hendren_eyeo_keynote/"
[[redirects]]
from="/thoughts-on-accessibility/"
to="/writing/2016-07-08-on_accessibility/"
[[redirects]]
from="/book-design-for-real-life/"
to="/writing/2016-03-10-book-design-for-real-life/"
[[redirects]]
from="/book-review-wild-ones/"
to="/writing/2016-01-24-book-wild-ones/"
[[redirects]]
from="/book-review-merchants-of-doubt/"
to="/writing/2016-01-24-book-merchants-of-doubt/"
[[redirects]]
from="/book-review-a-web-for-everyone/"
to="/writing/2016-01-24-book-a-web-for-everyone/"
[[redirects]]
from="/climate-change-science-settled/"
to="/writing/2016-01-11-climate-change-science-settled/"
[[redirects]]
from="/sady-doyle-on-pc-culture/"
to="/writing/2015-09-04-on-political-correctness/"
[[redirects]]
from="/agency-on-social-media/"
to="/writing/2015-09-03-agency-on-social-media/"
[[redirects]]
from="/recent-readings-links-aug-20-2015/"
to="/writing/2015-08-20-recent-reading-links/"
[[redirects]]
from="/documenting-considerations-and-complexities/"
to="/writing/2015-08-14-documenting-considerations-and-complexities/"
[[redirects]]
from="/omg-racked-published-me/"
to="/writing/2015-07-08-published-on-racked/"
[[redirects]]
from="/book-review-living-with-complexity/"
to="/writing/2015-07-29-living-with-complexity/"
[[redirects]]
from="/on-immunity"
to="/writing/2015-05-28-on-immunity/"
[[redirects]]
from="/thoughts-on-a-spring-day/"
to="/writing/2015-04-09-thoughts-on-a-spring-day/"
[[redirects]]
from="/friday-links-jan-30-2015/"
to="/writing/2015-01-30-friday-links-jobs/"
[[redirects]]
from="/january-perfomance-optimization/"
to="/writing/2015-01-25-site-performance-optimization/"
[[redirects]]
from="/thirty/"
to="/writing/2015-01-14-thirty/"
[[redirects]]
from="/book/2014/12/23/how-buildings-learn.html"
to="/writing/2014-12-23-how-buildings-learn/"
[[redirects]]
from="/friday-links-dec-5-2014/"
to="/writing/2014-12-05-friday-links/"
[[redirects]]
from="/gmaps-to-geojson/"
to="/writing/2014-12-01-convert-google-routes-to-geojson/"
[[redirects]]
from="/on-ferguson-im-listening/"
to="/writing/2014-11-25-on-ferguson/"
[[redirects]]
from="/how-buildings-learn-series/"
to="/writing/2014-11-24-how-buildings-learn-video/"
[[redirects]]
from="/chattanooga-story/"
to="/writing/2014-11-16-chattanooga-story/"
[[redirects]]
from="/friday-links-nov-14-2014/"
to="/writing/2014-11-14-friday-links-this-land/"
[[redirects]]
from="/book-review-bad-feminist/"
to="/writing/2014-11-11-bad-feminist/"
[[redirects]]
from="/friday-links-nov-7-2014/"
to="/writing/2014-11-07-friday-links/"
[[redirects]]
from="/embracing-the-existing/"
to="/writing/2014-10-28-embracing-the-existing/"
[[redirects]]
from="/the-ux-of-settling-in/"
to="/writing/2014-10-01-the-ux-of-settling-in/"
[[redirects]]
from="/javascript-promises-links/"
to="/writing/2014-09-19-javascript-promises-links/"
[[redirects]]
from="/missing-the-prose-for-the-grammar/"
to="/writing/2014-08-25-missing-the-prose-for-the-grammar/"
[[redirects]]
from="/surprise-youre-being-manipulated/"
to="/writing/2014-07-01-surprise-youre-being-manipulated/"
[[redirects]]
from="/introducing-playground/"
to="/writing/2014-04-21-introducing-playground/"
[[redirects]]
from="/why-i-dont-have-a-good-personal-site/"
to="/writing/2014-03-10-why-i-dont-have-a-good-portfolio/"
[[redirects]]
from="/on-accessibility/"
to="/writing/2014-02-28-on-accessibility/"
[[redirects]]
from="/sass-mixins-with-logic/"
to="/writing/2014-02-22-sass-mixins-with-logic/"

